---
title: "Codebook"
author: "Anugraha"
date: "20/06/2020"
output: html_document
---

The script run_analysis.R reads "Human activity data recorded by smart phones" from this source (http://archive.ics.uci.edu/ml/datasets/Human+Activity+Recognition+Using+Smartphones) and creates a tidy summarized data out of the experiment data.


### About the data:

The data set contains observations from experiments conducted in Smartlab - Non Linear Complex Systems Laboratory DITEN - Università degli Studi di Genova. The experiments were carried out with a group of 30 volunteers, each person performing six activities (WALKING, WALKING_UPSTAIRS, WALKING_DOWNSTAIRS, SITTING, STANDING, LAYING) wearing a smartphone (Samsung Galaxy S II) on the waist. Using embedded accelerometer and gyroscope, 3-axial linear acceleration and 3-axial angular velocity were recorded. 


### The original data has the following files:
>
1. features.txt - Has 561 variables of each feature vector 
2. activity labels - Has 6 activity types during which the observations were made
3. test data set - contains 30% volunteer data.
   + subject_test - 2947 observations - contains a column of numerical identifiers 
                                      that uniquely identifies a subject/participant.
   + x_test - (2947 rows, 561 columns)- contains values for all 561 feature variables observed
   + y_test - (2947 rows, 1 columns)  - contains list of activity labels from test dataset
4. train data set - contains 70% volunteer data
   + subject_train - 7352  observations - contains a column of numerical identifiers 
                                      that uniquely identifies a subject/participant.
   + x_train - (7352  rows, 561 columns)- contains values for all 561 feature variables observed
   + y_train - (7352  rows, 1 columns)  - contains list of activity labels from test dataset


### Tidy Data
The tidy data set obtained from merging the train and test datasets provides average of each variable for each activity and each subject. It has a total of 180 rows (30 volunteers*6 activity) with 88 columns of aggregated observations. Final columns names are:


str(final)


'data.frame':	180 obs. of  88 variables:

 $ Activity                                          | Factor w/ 6 levels "LAYING","SITTING",..: 1 1 1 1 1 1 1 1 1 1 ...
 $ subject                                           | int  1 2 3 4 5 6 7 8 9 10 ...
 $ TimeBodyAccelerometer.mean...X                    | num  0.222 0.281 0.276 0.264 0.278 ...
 $ TimeBodyAccelerometer.mean...Y                    | num  -0.0405 -0.0182 -0.019 -0.015 -0.0183 ...
 $ TimeBodyAccelerometer.mean...Z                    | num  -0.113 -0.107 -0.101 -0.111 -0.108 ...
 $ TimeGravityAccelerometer.mean...X                 | num  -0.249 -0.51 -0.242 -0.421 -0.483 ...
 $ TimeGravityAccelerometer.mean...Y                 | num  0.706 0.753 0.837 0.915 0.955 ...
 $ TimeGravityAccelerometer.mean...Z                 | num  0.446 0.647 0.489 0.342 0.264 ...
 $ TimeBodyAccelerometerJerk.mean...X                | num  0.0811 0.0826 0.077 0.0934 0.0848 ...
 $ TimeBodyAccelerometerJerk.mean...Y                | num  0.00384 0.01225 0.0138 0.00693 0.00747 ...
 $ TimeBodyAccelerometerJerk.mean...Z                | num  0.01083 -0.0018 -0.00436 -0.00641 -0.00304 ...
 $ TimeBodyGyroscope.mean...X                        | num  -0.01655 -0.01848 -0.02082 -0.00923 -0.02189 ...
 $ TimeBodyGyroscope.mean...Y                        | num  -0.0645 -0.1118 -0.0719 -0.093 -0.0799 ...
 $ TimeBodyGyroscope.mean...Z                        | num  0.149 0.145 0.138 0.17 0.16 ...
 $ TimeBodyGyroscopeJerk.mean...X                    | num  -0.107 -0.102 -0.1 -0.105 -0.102 ...
 $ TimeBodyGyroscopeJerk.mean...Y                    | num  -0.0415 -0.0359 -0.039 -0.0381 -0.0404 ...
 $ TimeBodyGyroscopeJerk.mean...Z                    | num  -0.0741 -0.0702 -0.0687 -0.0712 -0.0708 ...
 $ TimeBodyAccelerometerMagnitude.mean..             | num  -0.842 -0.977 -0.973 -0.955 -0.967 ...
 $ TimeGravityAccelerometerMagnitude.mean..          | num  -0.842 -0.977 -0.973 -0.955 -0.967 ...
 $ TimeBodyAccelerometerJerkMagnitude.mean..         | num  -0.954 -0.988 -0.979 -0.97 -0.98 ...
 $ TimeBodyGyroscopeMagnitude.mean..                 | num  -0.875 -0.95 -0.952 -0.93 -0.947 ...
 $ TimeBodyGyroscopeJerkMagnitude.mean..             | num  -0.963 -0.992 -0.987 -0.985 -0.986 ...
 $ FrequencyBodyAccelerometer.mean...X               | num  -0.939 -0.977 -0.981 -0.959 -0.969 ...
 $ FrequencyBodyAccelerometer.mean...Y               | num  -0.867 -0.98 -0.961 -0.939 -0.965 ...
 $ FrequencyBodyAccelerometer.mean...Z               | num  -0.883 -0.984 -0.968 -0.968 -0.977 ...
 $ FrequencyBodyAccelerometer.meanFreq...X           | num  -0.159 -0.146 -0.074 -0.274 -0.136 ...
 $ FrequencyBodyAccelerometer.meanFreq...Y           | num  0.0975 0.2573 0.2385 0.3662 0.4665 ...
 $ FrequencyBodyAccelerometer.meanFreq...Z           | num  0.0894 0.4025 0.217 0.2013 0.1323 ...
 $ FrequencyBodyAccelerometerJerk.mean...X           | num  -0.957 -0.986 -0.981 -0.979 -0.983 ...
 $ FrequencyBodyAccelerometerJerk.mean...Y           | num  -0.922 -0.983 -0.969 -0.944 -0.965 ...
 $ FrequencyBodyAccelerometerJerk.mean...Z           | num  -0.948 -0.986 -0.979 -0.975 -0.983 ...
 $ FrequencyBodyAccelerometerJerk.meanFreq...X       | num  0.132 0.16 0.176 0.182 0.24 ...
 $ FrequencyBodyAccelerometerJerk.meanFreq...Y       | num  0.0245 0.1212 -0.0132 0.0987 0.1957 ...
 $ FrequencyBodyAccelerometerJerk.meanFreq...Z       | num  0.0244 0.1906 0.0448 0.077 0.0917 ...
 $ FrequencyBodyGyroscope.mean...X                   | num  -0.85 -0.986 -0.97 -0.967 -0.976 ...
 $ FrequencyBodyGyroscope.mean...Y                   | num  -0.952 -0.983 -0.978 -0.972 -0.978 ...
 $ FrequencyBodyGyroscope.mean...Z                   | num  -0.909 -0.963 -0.962 -0.961 -0.963 ...
 $ FrequencyBodyGyroscope.meanFreq...X               | num  -0.00355 0.10261 -0.08222 -0.06609 -0.02272 ...
 $ FrequencyBodyGyroscope.meanFreq...Y               | num  -0.0915 0.0423 -0.0267 -0.5269 0.0681 ...
 $ FrequencyBodyGyroscope.meanFreq...Z               | num  0.0105 0.0553 0.1477 0.1529 0.0414 ...
 $ FrequencyBodyAccelerometerMagnitude.mean..        | num  -0.862 -0.975 -0.966 -0.939 -0.962 ...
 $ FrequencyBodyAccelerometerMagnitude.meanFreq..    | num  0.0864 0.2663 0.237 0.2417 0.292 ...
 $ FrequencyBodyAccelerometerJerkMagnitude.mean..    | num  -0.933 -0.985 -0.976 -0.962 -0.977 ...
 $ FrequencyBodyAccelerometerJerkMagnitude.meanFreq..| num  0.266 0.342 0.239 0.274 0.197 ...
 $ FrequencyBodyGyroscopeMagnitude.mean..            | num  -0.862 -0.972 -0.965 -0.962 -0.968 ...
 $ FrequencyBodyGyroscopeMagnitude.meanFreq..        | num  -0.1398 0.0186 -0.0229 -0.2599 0.1024 ...
 $ FrequencyBodyGyroscopeJerkMagnitude.mean..        | num  -0.942 -0.99 -0.984 -0.984 -0.985 ...
 $ FrequencyBodyGyroscopeJerkMagnitude.meanFreq..    | num  0.1765 0.2648 0.1107 0.2029 0.0247 ...
 $ Angle.TimeBodyAccelerometerMean.Gravity.          | num  0.02137 0.00579 0.0179 -0.00236 0.02121 ...
 $ Angle.TimeBodyAccelerometerJerkMean..GravityMean. | num  0.00306 -0.00636 0.01665 -0.0155 0.05536 ...
 $ Angle.TimeBodyGyroscopeMean.GravityMean.          | num  -0.00167 0.06529 0.04559 0.00713 -0.00581 ...
 $ Angle.TimeBodyGyroscopeJerkMean.GravityMean.      | num  0.0844 -0.0294 0.0317 0.0367 -0.0344 ...
 $ Angle.X.GravityMean.                              | num  0.427 0.617 0.424 0.553 0.599 ...
 $ Angle.Y.GravityMean.                              | num  -0.52 -0.52 -0.63 -0.763 -0.825 ...
 $ Angle.Z.GravityMean.                              | num  -0.352 -0.479 -0.346 -0.23 -0.168 ...
 $ TimeBodyAccelerometer.std...X                     | num  -0.928 -0.974 -0.983 -0.954 -0.966 ...
 $ TimeBodyAccelerometer.std...Y                     | num  -0.837 -0.98 -0.962 -0.942 -0.969 ...
 $ TimeBodyAccelerometer.std...Z                     | num  -0.826 -0.984 -0.964 -0.963 -0.969 ...
 $ TimeGravityAccelerometer.std...X                  | num  -0.897 -0.959 -0.983 -0.921 -0.946 ...
 $ TimeGravityAccelerometer.std...Y                  | num  -0.908 -0.988 -0.981 -0.97 -0.986 ...
 $ TimeGravityAccelerometer.std...Z                  | num  -0.852 -0.984 -0.965 -0.976 -0.977 ...
 $ TimeBodyAccelerometerJerk.std...X                 | num  -0.958 -0.986 -0.981 -0.978 -0.983 ...
 $ TimeBodyAccelerometerJerk.std...Y                 | num  -0.924 -0.983 -0.969 -0.942 -0.965 ...
 $ TimeBodyAccelerometerJerk.std...Z                 | num  -0.955 -0.988 -0.982 -0.979 -0.985 ...
 $ TimeBodyGyroscope.std...X                         | num  -0.874 -0.988 -0.975 -0.973 -0.979 ...
 $ TimeBodyGyroscope.std...Y                         | num  -0.951 -0.982 -0.977 -0.961 -0.977 ...
 $ TimeBodyGyroscope.std...Z                         | num  -0.908 -0.96 -0.964 -0.962 -0.961 ...
 $ TimeBodyGyroscopeJerk.std...X                     | num  -0.919 -0.993 -0.98 -0.975 -0.983 ...
 $ TimeBodyGyroscopeJerk.std...Y                     | num  -0.968 -0.99 -0.987 -0.987 -0.984 ...
 $ TimeBodyGyroscopeJerk.std...Z                     | num  -0.958 -0.988 -0.983 -0.984 -0.99 ...
 $ TimeBodyAccelerometerMagnitude.std..              | num  -0.795 -0.973 -0.964 -0.931 -0.959 ...
 $ TimeGravityAccelerometerMagnitude.std..           | num  -0.795 -0.973 -0.964 -0.931 -0.959 ...
 $ TimeBodyAccelerometerJerkMagnitude.std..          | num  -0.928 -0.986 -0.976 -0.961 -0.977 ...
 $ TimeBodyGyroscopeMagnitude.std..                  | num  -0.819 -0.961 -0.954 -0.947 -0.958 ...
 $ TimeBodyGyroscopeJerkMagnitude.std..              | num  -0.936 -0.99 -0.983 -0.983 -0.984 ...
 $ FrequencyBodyAccelerometer.std...X                | num  -0.924 -0.973 -0.984 -0.952 -0.965 ...
 $ FrequencyBodyAccelerometer.std...Y                | num  -0.834 -0.981 -0.964 -0.946 -0.973 ...
 $ FrequencyBodyAccelerometer.std...Z                | num  -0.813 -0.985 -0.963 -0.962 -0.966 ...
 $ FrequencyBodyAccelerometerJerk.std...X            | num  -0.964 -0.987 -0.983 -0.98 -0.986 ...
 $ FrequencyBodyAccelerometerJerk.std...Y            | num  -0.932 -0.985 -0.971 -0.944 -0.966 ...
 $ FrequencyBodyAccelerometerJerk.std...Z            | num  -0.961 -0.989 -0.984 -0.98 -0.986 ...
 $ FrequencyBodyGyroscope.std...X                    | num  -0.882 -0.989 -0.976 -0.975 -0.981 ...
 $ FrequencyBodyGyroscope.std...Y                    | num  -0.951 -0.982 -0.977 -0.956 -0.977 ...
 $ FrequencyBodyGyroscope.std...Z                    | num  -0.917 -0.963 -0.967 -0.966 -0.963 ...
 $ FrequencyBodyAccelerometerMagnitude.std..         | num  -0.798 -0.975 -0.968 -0.937 -0.963 ...
 $ FrequencyBodyAccelerometerJerkMagnitude.std..     | num  -0.922 -0.985 -0.975 -0.958 -0.976 ...
 $ FrequencyBodyGyroscopeMagnitude.std..             | num  -0.824 -0.961 -0.955 -0.947 -0.959 ...
 $ FrequencyBodyGyroscopeJerkMagnitude.std..         | num  -0.933 -0.989 -0.983 -0.983 -0.983 ...


