---
title: "README"
author: "Anugraha"
date: "20/06/2020"
output: html_document
---
ABOUT:

This project is done as part of the Coursera course "Getting and Cleaning data". The project contains an automated R script to read the dataset from here (http://archive.ics.uci.edu/ml/datasets/Human+Activity+Recognition+Using+Smartphones) and produce a tiday data set out of the study results.

---
Dataset

"Human Activity Recognition Using Smartphones"

The experiments have been carried out with a group of 30 volunteers within an age bracket of 19-48 years. Each person performed six activities (WALKING, WALKING_UPSTAIRS, WALKING_DOWNSTAIRS, SITTING, STANDING, LAYING) wearing a smartphone (Samsung Galaxy S II) on the waist. Using its embedded accelerometer and gyroscope, we captured 3-axial linear acceleration and 3-axial angular velocity at a constant rate of 50Hz. The experiments have been video-recorded to label the data manually. The obtained dataset has been randomly partitioned into two sets, where 70% of the volunteers was selected for generating the training data and 30% the test data.

---

Files

CodeBook.md - a code book that describes the variables, the data, and any transformations or work that I performed to clean up the data

run_analysis.R - automates the data download and pre-processing, followed by the 5 steps required as described in the course project’s definition:

1.Merges the training and the test sets to create one data set.
2.Extracts only the measurements on the mean and standard deviation for each measurement.
3.Uses descriptive activity names to name the activities in the data set
4.Appropriately labels the data set with descriptive variable names.
5.From the data set in step 4, creates a second, independent tidy data set with the average of each variable for each activity and each subject.

FinalData.txt is the exported final data after going through all the sequences described above.